# Generated by Django 5.1.7 on 2025-03-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_centerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
